services:
  postgres:
    image: postgres:latest
    container_name: futudurable
    environment:
      POSTGRES_DB: futudurable
      POSTGRES_USER: futudurable
      POSTGRES_PASSWORD: futudurable
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U futudurable -d futudurable-db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
