version: '3.8'

services:
  postgres_futudurable:
    image: postgres:latest
    container_name: futudurable
    environment:
      POSTGRES_DB: futudurable
      POSTGRES_USER: futudurable
      POSTGRES_PASSWORD: futudurable
    ports:
      - "5433:5432"  # Host port 5433 maps to container port 5432
    volumes:
      - postgres_data_futudurable:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U futudurable -d futudurable"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data_futudurable:
